-- DOO Extractor: converted job payload archive metadata
-- Run in Supabase SQL Editor (once).

create table if not exists public.doo_job_payload_meta (
  id bigint generated by default as identity primary key,
  job_id text not null unique,
  user_id text not null,
  user_email text null,
  payload_bucket text not null,
  payload_path text not null,
  source_hash text null,
  filename text null,
  project_name text null,
  mode text null,
  result_count integer not null default 0,
  uploaded_at timestamptz null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_doo_job_payload_meta_user_id
  on public.doo_job_payload_meta (user_id);

create index if not exists idx_doo_job_payload_meta_user_email
  on public.doo_job_payload_meta (user_email);

create unique index if not exists uq_doo_job_payload_meta_bucket_path
  on public.doo_job_payload_meta (payload_bucket, payload_path);

insert into storage.buckets (id, name, public)
values ('doo-job-payloads', 'doo-job-payloads', false)
on conflict (id) do nothing;
